# Generated by Django 5.1.1 on 2024-09-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cubes/')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('level', models.CharField(choices=[('1', 'BEGINNER'), ('2', 'INTERMEDIATE'), ('3', 'ADVANCE')], max_length=1)),
                ('duration', models.IntegerField()),
                ('mode', models.CharField(choices=[('ON', 'ONLINE'), ('OFF', 'OFFLINE')], max_length=3)),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
