# Generated by Django 5.1.1 on 2024-09-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_affiliates_certificate_coursereview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliates',
            name='course',
        ),
        migrations.AddField(
            model_name='affiliates',
            name='course',
            field=models.ManyToManyField(related_name='course', to='course.courses'),
        ),
    ]
