# Generated by Django 5.1.1 on 2024-09-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_affiliates_commission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='level',
            field=models.CharField(choices=[('BEGINNER', 1), ('INTERMEDIATE', 2), ('ADVANCE', 3)], max_length=100),
        ),
    ]
