# Generated by Django 5.1.1 on 2024-09-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_courses_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliates',
            name='mode',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], max_length=50),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='rating',
            field=models.CharField(choices=[('WORST', 'Worst'), ('BAD', 'Bad'), ('GOOD', 'Good'), ('BETTER', 'Better'), ('BEST', 'Best')], max_length=50),
        ),
        migrations.AlterField(
            model_name='courses',
            name='mode',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], max_length=50),
        ),
    ]
