# Generated by Django 5.1.1 on 2024-09-24 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_affiliates_mode_alter_coursereview_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliates',
            name='mode',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=50),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.courses'),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='rating',
            field=models.CharField(choices=[('Worst', 'Worst'), ('Bad', 'Bad'), ('Good', 'Good'), ('Better', 'Better'), ('Best', 'Best')], max_length=50),
        ),
        migrations.AlterField(
            model_name='courses',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='courses',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advance', 'Advance')], max_length=100),
        ),
        migrations.AlterField(
            model_name='courses',
            name='mode',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=50),
        ),
        migrations.AlterField(
            model_name='courses',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
